services:
  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION:-latest}
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
      KC_HOSTNAME: ${KC_HOSTNAME:-localhost}
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_DB: ${KC_DB:-h2} # Use 'postgres' para PostgreSQL, 'mysql' para MySQL, etc.
      KC_DB_URL: ${KC_DB_URL:-jdbc:h2:mem:keycloak;DB_CLOSE_DELAY=-1;MODE=PostgreSQL} # Ajuste para seu banco
      KC_DB_USERNAME: ${KC_DB_USERNAME:-sa} # Ajuste para seu banco
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-sa} # Ajuste para seu banco
      KC_HEALTH_ENABLED: "true"
    volumes:
      - keycloak_data:/opt/keycloak/data # Para persistir dados (opcional, mas recomendado para produção)
    command: start --optimized
    restart: unless-stopped
    networks:
      - keycloak-network

volumes:
  keycloak_data:
    driver: local

networks:
  keycloak-network:
    driver: bridge