services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    labels:
      - br.dev.robsonalves.service.group=keycloak
      - br.dev.robsonalves.service.version=26.1.4
      - br.dev.robsonalves.service.description=Keycloak
    container_name: keycloak
    restart: unless-stopped
    command: --verbose start-dev --import-realm
    volumes:
      - ./realm-export:/opt/keycloak/data/import
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-password}
      - KC_DB=${KC_DB:-postgres}
      - KC_DB_URL_HOST=${KC_DB_URL_HOST:-db-keycloak}  
      - KC_DB_USERNAME=${KC_DB_USERNAME:-keycloak}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD:-keycloak}    
    ports:
      - "8080:8080"
    depends_on:
      - db-keycloak

  db-keycloak:
    image: postgres:17.4-alpine
    labels:
      - br.dev.robsonalves.service.group=keycloak
      - br.dev.robsonalves.service.version=17.4-alpine
      - br.dev.robsonalves.service.description=PostgreSQL
    container_name: db-keycloak
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-keycloak}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-keycloak}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --data-checksums
    ports:
      - "5432:5432"


  # keycloak:
  #   image: quay.io/keycloak/keycloak:22.0.0
  #   container_name: keycloak
  #   restart: unless-stopped
  #   command: --verbose start-dev
  #   environment:
  #     - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
  #     - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-password}
  #     - KC_DB=${KC_DB:-postgres}
  #     - KC_DB_URL_HOST=${KC_DB_URL_HOST:-db-keycloak}
  #     - KC_DB_USERNAME=${KC_DB_USERNAME:-keycloak}
  #     - KC_DB_PASSWORD=${KC_DB_PASSWORD:-keycloak}
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db-keycloak

  # db-keycloak:
  #   image: postgres:15.3-alpine
  #   container_name: db-keycloak
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER:-keycloak}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-keycloak}
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF8 --data-checksums
  #   ports:
  #     - "5432:5432"