services:
  # keycloak:
  #   image: quay.io/keycloak/keycloak:22.0.0
  #   container_name: keycloak
  #   restart: unless-stopped
  #   command: --verbose start-dev
  #   environment:
  #     - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
  #     - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-password}
  #     - KC_DB=${KC_DB:-postgres}
  #     - KC_DB_URL_HOST=${KC_DB_URL_HOST:-db-keycloak}
  #     - KC_DB_USERNAME=${KC_DB_USERNAME:-keycloak}
  #     - KC_DB_PASSWORD=${KC_DB_PASSWORD:-keycloak}
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db-keycloak

  # db-keycloak:
  #   image: postgres:15.3-alpine
  #   container_name: db-keycloak
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER:-keycloak}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-keycloak}
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF8 --data-checksums
  #   ports:
  #     - "5432:5432"


  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    restart: unless-stopped
    command: --verbose start-dev
    #command: start-dev --db postgres --db-url-host db-keycloak --db-username keycloak --db-password keycloak
    #command: start-dev --db ${KC_DB:-postgres} --db-url-host ${KC_DB_HOST:-db-keycloak} --db-username ${POSTGRES_USER:-keycloak} --db-password ${POSTGRES_PASSWORD:-keycloak}
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KEYCLOAK_ADMIN:-admin}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-password}
      - KC_DB=${KC_DB:-postgres}
      - KC_DB_URL_HOST=${KC_DB_URL_HOST:-db-keycloak}  
      - KC_DB_USERNAME=${KC_DB_USERNAME:-keycloak}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD:-keycloak}
    ports:
      - "8080:8080"
    depends_on:
      - db-keycloak

  db-keycloak:
    image: postgres:17.4-alpine
    container_name: db-keycloak
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-keycloak}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-keycloak}
      - POSTGRES_INITDB_ARGS=--encoding=UTF8 --data-checksums
    ports:
      - "5432:5432"