services:
  # keycloak-22:
  #   image: quay.io/keycloak/keycloak:22.0.0
  #   container_name: keycloak-22
  #   command: start-dev
  #   environment:
  #     - KEYCLOAK_ADMIN=admin
  #     - KEYCLOAK_ADMIN_PASSWORD=admin
  #     - KC_DB=postgres
  #     - KC_DB_URL=jdbc:postgresql://db-22:5432/keycloak
  #     - KC_DB_USERNAME=keycloak
  #     - KC_DB_PASSWORD=keycloak
  #     - POSTGRES_VERSION=15
  #     - KC_BOOTSTRAP_ADMIN_USERNAME=admin
  #     - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - db-22

  # db-22:
  #   image: postgres:15.3-alpine
  #   container_name: db-22
  #   environment:
  #     - POSTGRES_USER=keycloak
  #     - POSTGRES_PASSWORD=keycloak
  #     - POSTGRES_DB=keycloak
  #   ports:
  #     - "5432:5432"


  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: keycloak
    command: start-dev --db postgres --db-url-host db-keycloak --db-username keycloak --db-password keycloak
    environment:
      #- KEYCLOAK_ADMIN=admin
      #- KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-admin}
      #- KC_HOSTNAME=${KC_HOSTNAME:-localhost}
      
      #- KC_DB=postgres
      #- KC_DB_URL=jdbc:postgresql://db-keycloak:5432/keycloak
      #- KC_DB_USERNAME=keycloak
      #- KC_DB_PASSWORD=keycloak
      #- KC_DB_URL_PORT=6432
      #- POSTGRES_VERSION=17
      #- KC_BOOTSTRAP_ADMIN_USERNAME=admin
      #- KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    ports:
      - "8080:8080"
    depends_on:
      - db-keycloak

  db-keycloak:
    image: postgres:17.4-alpine
    container_name: db-keycloak
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    ports:
      - "5432:5432"