@baseUrl = localhost:8080
@realm = myrealm
@client-public = myclient-public
@client-public-accessgrant = myclient-public-accessgrant
@username = robson@testuser.com
@password = keycloak@2025
@code_verifier = FOJiVKUZC0CtLtRi_qURIE-iiGL2Xq2qGVHhjX4uZ-U
@code_challenge = L7hjTyG4QAdn6r_KdeZenzqc2oIOc99uu2r2y_CrZbU
@state = 1234567890
@redirect_uri = http://localhost:8080/realms/myrealm/protocol/openid-connect/auth


### Autenticando com cliente publico com concessão de acesso
### -------------------------------------------------------------------------------
POST http://{{baseUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{username}}
&password={{password}}
&client_id={{client-public-accessgrant}}



### Autenticando com cliente publico sem concessão de acesso
POST http://{{baseUrl}}/realms/{{realm}}/protocol/openid-connect/auth
Content-Type: application/x-www-form-urlencoded

response_type=code
&client_id={{client-public}}
&redirect_uri={{redirect_uri}}
&scope=openid profile email
&state={{state}}
&code_challenge={{code_challenge}}
&code_challenge_method=S256



### New Section
### -------------------------------------------------------------------------------
POST http://{{baseUrl}}/realms/{{realm}}/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code
&client_id={{client-public}}
&code=17792c1e-c62e-446f-94b2-d212eb938404.b671fdb5-f91b-4573-9a02-5dfee355c97f.1a05dfe0-9467-4fd6-af8a-c5017df2b86b
&redirect_uri={{redirect_uri}}
&code_verifier={{code_verifier}}


# ### Get User Info
# ### -------------------------------------------------------------------------------
# GET http://localhost:8080/realms/myrealm/protocol/openid-connect/userinfo
# Authorization: Bearer {{token}}



### Get Keycloak Admin Token
### -------------------------------------------------------------------------------
POST http://localhost:8080/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=admin-cli&username=admin&password=admin



# ### Get Users
# ### -------------------------------------------------------------------------------
# GET http://localhost:8080/admin/realms/myrealm/users
# Authorization: Bearer {{adminToken}}
