### Get Keycloak Token
POST http://localhost:8080/realms/myrealm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

username=robson
&password=password
&grant_type=password
&client_id=myclient

### Get User Info
GET http://localhost:8080/realms/myrealm/protocol/openid-connect/userinfo
Authorization: Bearer {{token}}

### Get Keycloak Admin Token
POST http://localhost:8080/realms/master/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=admin-cli&username=admin&password=admin

### Get Users
GET http://localhost:8080/admin/realms/myrealm/users
Authorization: Bearer {{adminToken}}
